#!/bin/bash

set -e

pacman -S linux linux-headers linux-lts linux-lts-headers <<EEOF



EEOF

pacman -S vim base-devel networkmanager lvm2 <<EEOF




EEOF

systemctl enable NetworkManager

sed -i 's/block filesystems/block encrypt lvm2 filesystems/g' /etc/mkinitcpio.conf

mkinitcpio -p linux
mkinitcpio -p linux-lts

sed -i 's/#en_US.UTF-8/en_US.UTF-8/g'/etc/locale.gen
local-gen

echo Root password
passwd
echo User name
read username
useradd -m -g user -G wheel $username
passwd $username

if [ ! -f $(which sudo)  ]; then
	pacman -S sudo <<EEOF


EEOF
fi

visudo <<EEOF
/# %wheel ALL=(ALL) ALL

EEOF
